services:
  identity:
    build:
      secrets:
        - tls-password
        - tls-ca-password
      args:
        AIA_URL_SERVER_PORT: :4443

    ports:
#      - host_ip: 127.0.0.1
      - "8080:80"
      - "4443:443"

    secrets:
      - tls-password
      - tls-ca-password

#    entrypoint: /bin/sh
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t


secrets:
  tls-password:
    file: ./tls-password.txt
  tls-ca-password:
    file: ./tls-ca-password.txt